### ISSUE TITLE
Add Reader just like Writer

### ISSUE THREAD

**Issue by yakuter** [binalyze/ctxio#1]
In some situations, you can't set writer. So we also need the Reader version of the current Writer.

**Comment by gozeloglu** [comment]
Hi @yakuter. I'd like to take that issue. Maybe I'll need help from you to make issue clear.

**Comment by yakuter** [comment]
Let's wait and see if a newcomer want to do this. If not I will assign you. Thank you.

**Comment by gozeloglu** [comment]
Okay. I'm ready to fix that issue.

**Comment by yakuter** [comment]
OK @gozeloglu I've just assigned you. Let's do this.

**Comment by gozeloglu** [comment]
Thanks. I'll try to add that feature. But, I will be travelling tomorrow. That's why it can take 2-3 days.
